import funsets.FunSets._

val s1 = singletonSet(1)
val s2 = singletonSet(2)
val s3 = singletonSet(3)
val s4 = union(s1, s2)
val s5 = union(s2, s3)
val s6=intersect(s4,s5)
val s7=diff(s4,s5)
val s8=filter(s4,x=>x>1)
forall(s4,x=>x>1)
forall(s4,x=>x>0)
exists(s4,x=>x>1)
exists(s4,x=>x>2)
val s9=map(s4,x=>x*2)
printSet(s4)
printSet(s6)
printSet(s7)
printSet(s8)
printSet(s9)